dtm/urls.py
from .utils import re_path
from . import views

app_name = 'dtm'

urlpatterns = [
    re_path('^$', views.translations_list, name='list'),
    re_path('^download/$', views.download, name='download'),
    re_path('^upload/$', views.upload, name='upload')
]

dtm/views/download.py
import os
from contextlib import suppress

from django.http import Http404
from django import forms
from django.shortcuts import redirect

from django_sendfile import sendfile

from dtm.utils import only_superuser, reverse
from .utils import FilePathForm, handle_form


@only_superuser
def download(request):
    form = FilePathForm(request.GET)

    with suppress(forms.ValidationError):
        with handle_form(request, form):
            path = form.cleaned_data['path']
            name = '-'.join(path.split('/')[-5:])

            return sendfile(
                request, path, attachment=True, attachment_filename=name
            )

    return redirect(reverse('dtm:list'))

dtm/views/list.py
from django.template.response import SimpleTemplateResponse, TemplateResponse

from dtm.services import locator
from dtm.utils import only_superuser
from .utils import get_available_languages


def prepare_file_item(file):
    return {
        'path': file,
        'name': '/'.join(file.split('/')[-5:])
    }


def prepare_objects(languages, files):
    return [
        {
            'code': language,
            'name': languages[language],
            'files': list(map(prepare_file_item, files[language]))
        }
        for language in languages
        if language in files
    ]


@only_superuser
def translations_list(request):
    languages = get_available_languages()
    objects = {
        'project': prepare_objects(
            languages, locator.locate(languages=languages, is_project=True)
        ),
        'django': prepare_objects(
            languages, locator.locate(
                languages=languages, paths=[], is_django=True
            )
        ),
        'third_party': prepare_objects(
            languages, locator.locate(
                languages=languages, paths=[], is_third_party=True
            )
        )
    }

    return TemplateResponse(request, [
        'dtm/admin/list_translations.html'
    ], {
        'objects': objects
    })

dtm/views/upload.py
import os
from contextlib import suppress

from django.http import Http404
from django.core.validators import FileExtensionValidator
from django import forms
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _

from django_sendfile import sendfile

from dtm.utils import only_superuser, reverse
from dtm.services import inserter
from .utils import FilePathForm, handle_form


class UploadForm(FilePathForm):
    file = forms.FileField(
        required=True,
        validators=[FileExtensionValidator(['po'])]
    )


@only_superuser
def upload(request):
    form = UploadForm(request.POST, files=request.FILES)

    with suppress(forms.ValidationError):
        with handle_form(
            request, form, success_message=_('File upload successful.')
        ):
            inserter.insert(
                path=form.cleaned_data['path'],
                file=form.cleaned_data['file']
            )

    return redirect(reverse('dtm:list'))

dtm/views/utils.py
import os
from itertools import chain
from contextlib import contextmanager

from django.contrib import messages
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django import forms

from dtm.services import locator


__all__ = (
    'get_available_languages',
    'get_available_files',
    'is_available',
    'message_form_errors',
    'handle_form',
    'FilePathForm'
)


def get_available_languages():
    return {
        code: _(name) for code, name in settings.LANGUAGES
    }


def get_available_files():
    located = locator.locate(
        languages=get_available_languages(),
        is_django=True,
        is_project=True,
        is_third_party=True
    )

    return set(chain(*(
        files for language, files in located.items()
    )))


def is_available(file):
    return file in get_available_files()


def message_form_errors(request, form):
    for key, errors in form.errors.items():
        for error in errors:
            messages.add_message(request, messages.ERROR, error)


@contextmanager
def handle_form(request, form, success_message=None):
    valid = form.is_valid()

    if not valid:
        message_form_errors(request, form)
        raise forms.ValidationError(None)

    try:
        yield form

        if (success_message is not None):
            messages.add_message(request, messages.SUCCESS, success_message)

    except Exception as e:
        messages.add_message(
            request, messages.ERROR, 'Internal error: {}'.format(e)
        )


class FilePathForm(forms.Form):
    path = forms.CharField(required=True)

    def clean_path(self):
        value = self.cleaned_data.get('path', '')

        if not os.path.isfile(value) or not is_available(value):
            raise forms.ValidationError('Wrong file destination provided.')

        if not os.access(value, os.W_OK):
            raise forms.ValidationError('File is not writable.')

        return value

dtm/templates/dtm/admin/list.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}">
{% endblock %}

{% block bodyclass %}{{ block.super }} app-dtm change-list{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Application translations' %}
</div>
{% endblock %}

{% block coltype %}flex{% endblock %}

{% block content %}
<div id="content-main">
    {% block object-tools %}
    <ul class="object-tools">
    </ul>
    {% endblock %}

    {% block result_list %}

    {% endblock %}
</div>
{% endblock %}

dtm/templates/dtm/admin/list_translations--section.html
{% load i18n admin_urls static admin_list %}

{% for language in section %}
    <div class="module">
        <div class="results">
            <h2>
                {{ language.name }} <small>({{ language.code }})</small>
            </h2>
            <table>
                <thead>
                    <tr>
                        <th scope="col" class="column-file-path">
                            <div class="text"><span>{% trans 'File path' %}</span></div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col" colspan="2" class="column-actions action-checkbox-column">
                            <div class="text"><span></span></div>
                            <div class="clear"></div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in language.files %}
                        <tr class="row1">
                            <th class="field-file-path">{{ file.name }}</th>
                            <th class="action-checkbox-column" style="text-align: right">
                                    <form
                                        method="post"
                                        enctype="multipart/form-data"
                                        action="{% url 'dtm:upload' %}"
                                        novalidate
                                    >
                                        {% csrf_token %}
                                        <input type="hidden" name="path" value="{{ file.path }}" />
                                        <label style="cursor: pointer">
                                            <input type="file" name="file" style="display: none" class="js-autosubmit" />
                                            <span class="addlink">{% trans 'Upload' %}</span>
                                        </label>
                                        <input type="submit" style="display: none" />
                                    </form>
                                </div>
                            </th>
                            <th class="field-actions action-checkbox-column" style="text-align: right">
                                <a href="{% url 'dtm:download' %}?path={{ file.path|urlencode }}">Download</a>
                            </th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% empty %}

<ul class="messagelist">
    <li class="warning">There is no files in this section.</li>
</ul>

{% endfor %}

dtm/templates/dtm/admin/list_translations.html
{% extends "dtm/admin/list.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrahead %}
{{ block.super }}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script>
    $(function() {
        $('.js-autosubmit').on('change', function(e) {

            if (e.target.value && e.target.form) {
                e.target.form.submit();
            }
        });
    });
</script>

<style>

.hoverable-highlight {
    opacity: 0.5;
}

.hoverable-highlight:hover {
    opacity: 1;
}

</style>

{% endblock %}

{% block result_list %}

<div id="changelist">
    <div class="module">
        <h1>
            <span style="font-size: 1.4em;">{% trans 'Project translations' %}</span>
            <div class="help">
                {% blocktrans %}
                    This is the main section, where most of translation texts are located.
                    Other sections may be changed, but most of time it's an unnecessary action.
                {% endblocktrans %}
            </div>
        </h1>
        {% include "dtm/admin/list_translations--section.html" with section=objects.project %}
    </div>
    <!--
    <div class="module"><br/><br/><br/><br/><br/><br/></div>

    <div class="hoverable-highlight">
        <div class="module">
            <h1>{% trans 'Third party translations' %}</h1>
            {% include "dtm/admin/list_translations--section.html" with section=objects.third_party %}
        </div>

        <div class="module">
            <h1>{% trans 'Django internal translations' %}</h1>
            {% include "dtm/admin/list_translations--section.html" with section=objects.django %}
        </div>
    </div>
    -->
</div>

{% endblock %}

dtm/templates/dtm/admin_index.html
{% extends "admin/index.html" %}
{# {% extends "rosetta/admin_index.html" %} #}

{% load rosetta i18n %}

{% block sidebar %}
{{block.super}}
{% if request.user|can_translate  %}
<div id="dtm-content-main">
  <div class="app-dtm module">
    <table>
      <caption>
          <a class="section" href="{% url 'dtm:list' %}">Django Translations Management</a>
      </caption>
      <tbody><tr>
          <th scope="row"><a href="{% url 'dtm:list' %}">{% trans "Application translations" %}</a></th>
          <td colspan="2"><a href="{% url 'dtm:list' %}" class="changelink">{% trans "Change" %}</a></td>
        </tr>
      </tbody></table>
  </div>
</div>
{% endif %}
{% endblock %}